import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { User } from "@shared/schema";
import { formatCurrency } from "./currency-utils";

/**
 * PDF Generation utilities for RentFlow
 * Common functions for creating professional PDF reports
 */

export interface PDFHeader {
    companyName: string;
    businessAddress?: string;
    businessEmail?: string;
    phone?: string;
}

export function addPDFHeader(doc: jsPDF, user: User, title: string) {
    const pageWidth = doc.internal.pageSize.getWidth();

    // Company/User info (top left)
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(user.companyName || "RentFlow", 20, 20);

    let yPos = 28;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    if (user.businessAddress) {
        doc.text(user.businessAddress, 20, yPos);
        yPos += 5;
    }
    if (user.businessEmail) {
        doc.text(user.businessEmail, 20, yPos);
        yPos += 5;
    }
    if (user.phone) {
        doc.text(user.phone, 20, yPos);
    }

    // Document title (top right)
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    const titleWidth = doc.getTextWidth(title);
    doc.text(title, pageWidth - titleWidth - 20, 20);

    // Date (below title)
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const dateStr = new Date().toLocaleDateString();
    const dateWidth = doc.getTextWidth(dateStr);
    doc.text(dateStr, pageWidth - dateWidth - 20, 28);

    // Horizontal line
    doc.setLineWidth(0.5);
    doc.line(20, 40, pageWidth - 20, 40);

    return 50; // Return Y position for content to start
}

export function addPDFFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(128);

    // Page number (center)
    const pageText = `Page ${pageNumber} of ${totalPages}`;
    const pageTextWidth = doc.getTextWidth(pageText);
    doc.text(pageText, (pageWidth - pageTextWidth) / 2, pageHeight - 10);

    // Footer text (left)
    doc.text("Generated by RentFlow Property Management", 20, pageHeight - 10);

    doc.setTextColor(0);
}

export function createPDFDocument(): jsPDF {
    return new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });
}

export function savePDF(doc: jsPDF, filename: string) {
    doc.save(`${filename}.pdf`);
}
